### ISSUE TITLE
If i add "Usera-agent" header, i have 2 "User-agent"

### ISSUE THREAD

**Issue by fleytman** [dipu-bd/pyease-grpc#3]
```python
    user_agent = "grpc-web-javascript/0.1"
    headers = {
        "User-agnet": user_agent
    }
    response = session.request(
        RpcUri(url, package=package,
               service=service, method=method),
        headers=headers,
        data=data
```

<img width="458" alt="Screenshot 2022-11-28 at 10 52 20" src="https://user-images.githubusercontent.com/1923645/204236377-bf4367b3-94fe-4378-9062-bc867be3c432.png">

It's problem for my api

**Comment by dipu-bd** [comment]
Check the spelling. One is `User-Agent` another is `User-agnet`. You switched the place for n and e for agent.

**Comment by fleytman** [comment]
Sorry, realy it's my mistake
